# Generated by Django 4.2.16 on 2026-09-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.TextField(help_text='Markdown content', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_uz',
            field=models.TextField(help_text='Markdown content', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_en',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_uz',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uz',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
