# Generated by Django 4.2.16 on 2026-09-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_backfill_uz_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Avtomatik hisoblanadi — har bir tashrifchi bir marta'),
        ),
    ]
