# Generated by Django 4.2.16 on 2026-04-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='bio_photos/'),
        ),
    ]
