# Generated by Django 4.2.16 on 2026-04-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_bio_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload PDF resume', null=True, upload_to='resumes/'),
        ),
    ]
