# Generated by Django 4.2.16 on 2026-09-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='bio_text_en',
            field=models.TextField(help_text='Markdown-formatted bio', null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='bio_text_uz',
            field=models.TextField(help_text='Markdown-formatted bio', null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_uz',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
