# Generated by Django 4.2.16 on 2026-09-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(help_text='post | lecture', max_length=30)),
                ('object_id', models.PositiveIntegerField()),
                ('visitor_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Ko'rish",
                'verbose_name_plural': "Ko'rishlar",
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='analytics_v_content_e5293e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='viewrecord',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'visitor_hash'), name='unique_view_per_visitor'),
        ),
    ]
