# Generated by Django 4.2.16 on 2026-04-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tech_tags',
            field=models.CharField(blank=True, default='', help_text='Technologies separated by commas, e.g. Django, React, Tailwind', max_length=500),
        ),
    ]
