# Generated by Django 5.1.15 on 2026-04-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("backend", "Backend"),
                    ("frontend", "Frontend"),
                    ("fullstack", "Fullstack"),
                    ("infrastructure", "Infrastructure"),
                    ("devops", "Devops"),
                ],
                default="backend",
                max_length=30,
            ),
        ),
    ]
