# Generated by Django 5.1.15 on 2026-04-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="stat1_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. requests / second",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="stat1_value",
            field=models.CharField(
                blank=True, default="", help_text="e.g. 50k+", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="stat2_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. avg response time",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="stat2_value",
            field=models.CharField(
                blank=True, default="", help_text="e.g. ~38ms", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="stat3_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. uptime last 12 months",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="stat3_value",
            field=models.CharField(
                blank=True, default="", help_text="e.g. 99.97%", max_length=50
            ),
        ),
    ]
