# Generated by Django 5.1.15 on 2026-04-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_stat1_label_project_stat1_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Tafsiya: 1920x1080 yoki 1280x720 o'lchamdagi gorizontal .webp, .jpg, .png rasm yuklang",
                null=True,
                upload_to="project_covers/",
            ),
        ),
    ]
