# Generated by Django 4.2.16 on 2026-04-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sponsor_url',
            field=models.URLField(blank=True, default='', help_text='Optional: GitHub Sponsors or similar link. Leave blank to hide the button.'),
        ),
    ]
