# Generated by Django 4.2.16 on 2026-09-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(help_text='Masalan: Senior Developer', max_length=150)),
                ('role_uz', models.CharField(help_text='Masalan: Senior Developer', max_length=150, null=True)),
                ('role_en', models.CharField(help_text='Masalan: Senior Developer', max_length=150, null=True)),
                ('company', models.CharField(blank=True, default='', help_text='Masalan: Google', max_length=150)),
                ('company_uz', models.CharField(blank=True, default='', help_text='Masalan: Google', max_length=150, null=True)),
                ('company_en', models.CharField(blank=True, default='', help_text='Masalan: Google', max_length=150, null=True)),
                ('description', models.TextField(blank=True, default='', help_text="Nima o'rgatgani haqida")),
                ('description_uz', models.TextField(blank=True, default='', help_text="Nima o'rgatgani haqida", null=True)),
                ('description_en', models.TextField(blank=True, default='', help_text="Nima o'rgatgani haqida", null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='mentor_photos/')),
                ('initials', models.CharField(blank=True, default='', help_text="Rasm bo'lmasa ko'rsatiladi. Bo'sh qoldirilsa ismdan olinadi.", max_length=4)),
                ('accent_color', models.CharField(blank=True, default='#7C3AED', help_text='Avatar va karta foni uchun HEX rang', max_length=7)),
                ('tags', models.CharField(blank=True, default='', help_text='Vergul bilan ajrating: JavaScript, Architecture', max_length=300)),
                ('profile_url', models.URLField(blank=True, default='', help_text='LinkedIn, GitHub yoki shaxsiy sayt')),
                ('is_featured', models.BooleanField(default=False, help_text="Bosh sahifada ko'rsatilsinmi")),
                ('order', models.PositiveIntegerField(default=0, help_text='Kichik raqam = yuqorida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ustoz',
                'verbose_name_plural': 'Ustozlar',
                'ordering': ['order', 'id'],
            },
        ),
    ]
