# Generated by Django 4.2.16 on 2026-04-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('youtube_video_id', models.CharField(help_text='YouTube video ID (e.g. dQw4w9WgXcQ)', max_length=20)),
                ('category', models.CharField(choices=[('database', 'Database'), ('networking', 'Networking'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('devops', 'DevOps'), ('algorithms', 'Algorithms'), ('general', 'General')], default='general', max_length=30)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Video duration in seconds')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
