# Generated by Django 4.2.16 on 2026-04-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
