# Generated by Django 4.2.16 on 2026-06-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_lecture_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecture_video',
            field=models.FileField(blank=True, null=True, upload_to='lectures/videos/'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text='YouTube video ID (e.g. dQw4w9WgXcQ)', max_length=20, null=True),
        ),
    ]
