# Generated by Django 4.2.16 on 2026-06-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_lecture_lecture_video_alter_lecture_youtube_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text='YouTube video ID or full YouTube URL (e.g. dQw4w9WgXcQ)', max_length=500, null=True),
        ),
    ]
