# Generated by Django 4.2.16 on 2026-09-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_alter_lecture_youtube_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='title_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='title_uz',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
