# Generated by Django 4.2.16 on 2026-09-02 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0006_backfill_uz_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('title_uz', models.CharField(max_length=250, null=True)),
                ('title_en', models.CharField(max_length=250, null=True)),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('description_uz', models.TextField(blank=True, default='', null=True)),
                ('description_en', models.TextField(blank=True, default='', null=True)),
                ('category', models.CharField(choices=[('database', 'Database'), ('networking', 'Networking'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('devops', 'DevOps'), ('algorithms', 'Algorithms'), ('general', 'General')], default='general', max_length=30)),
                ('accent_color', models.CharField(blank=True, default='#7C3AED', help_text='Karta gradienti uchun HEX rang', max_length=7)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='course_covers/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Kichik raqam = yuqorida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lecture',
            name='views_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Avtomatik hisoblanadi — har bir tashrifchi bir marta'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Qaysi kursga tegishli (ixtiyoriy)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures', to='lectures.course'),
        ),
    ]
