# Generated by Django 4.2.16 on 2026-04-04 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('preferred_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=300)),
                ('topic', models.TextField(help_text='What would you like to discuss? (20–600 characters)', validators=[django.core.validators.MinLengthValidator(20), django.core.validators.MaxLengthValidator(600)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
