# Generated by Django 4.2.16 on 2026-09-02 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_uz', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Sarlavha ostidagi qisqa izoh', max_length=300)),
                ('subtitle_uz', models.CharField(blank=True, default='', help_text='Sarlavha ostidagi qisqa izoh', max_length=300, null=True)),
                ('subtitle_en', models.CharField(blank=True, default='', help_text='Sarlavha ostidagi qisqa izoh', max_length=300, null=True)),
                ('description', models.TextField(help_text='Karta uchun qisqa tavsif')),
                ('description_uz', models.TextField(help_text='Karta uchun qisqa tavsif', null=True)),
                ('description_en', models.TextField(help_text='Karta uchun qisqa tavsif', null=True)),
                ('overview', models.TextField(blank=True, default='', help_text="'Loyiha haqida' bo'limi — to'liq tavsif")),
                ('overview_uz', models.TextField(blank=True, default='', help_text="'Loyiha haqida' bo'limi — to'liq tavsif", null=True)),
                ('overview_en', models.TextField(blank=True, default='', help_text="'Loyiha haqida' bo'limi — to'liq tavsif", null=True)),
                ('work_type', models.CharField(choices=[('web_app', 'Web App'), ('mobile', 'Mobile'), ('api', 'API'), ('open_source', 'Open Source'), ('other', 'Boshqa')], default='web_app', max_length=30)),
                ('status', models.CharField(choices=[('production', 'Production'), ('beta', 'Beta'), ('archived', 'Archived'), ('in_progress', 'Ishlanmoqda')], default='production', max_length=30)),
                ('cover_image', models.ImageField(blank=True, help_text='Tavsiya: 1920x1080 yoki 1280x720 gorizontal rasm', null=True, upload_to='work_covers/')),
                ('accent_color', models.CharField(blank=True, default='#7C3AED', help_text='Karta gradienti uchun HEX rang, masalan #7C3AED', max_length=7)),
                ('tech_tags', models.CharField(blank=True, default='', help_text='Vergul bilan ajrating: React, Node.js, PostgreSQL', max_length=500)),
                ('github_url', models.URLField(blank=True, default='')),
                ('live_url', models.URLField(blank=True, default='')),
                ('sponsor_url', models.URLField(blank=True, default='')),
                ('role', models.CharField(blank=True, default='', help_text='Masalan: Fullstack Developer', max_length=150)),
                ('role_uz', models.CharField(blank=True, default='', help_text='Masalan: Fullstack Developer', max_length=150, null=True)),
                ('role_en', models.CharField(blank=True, default='', help_text='Masalan: Fullstack Developer', max_length=150, null=True)),
                ('duration', models.CharField(blank=True, default='', help_text='Masalan: 6 oy', max_length=100)),
                ('duration_uz', models.CharField(blank=True, default='', help_text='Masalan: 6 oy', max_length=100, null=True)),
                ('duration_en', models.CharField(blank=True, default='', help_text='Masalan: 6 oy', max_length=100, null=True)),
                ('team_size', models.CharField(blank=True, default='', help_text='Masalan: 4 kishi', max_length=100)),
                ('team_size_uz', models.CharField(blank=True, default='', help_text='Masalan: 4 kishi', max_length=100, null=True)),
                ('team_size_en', models.CharField(blank=True, default='', help_text='Masalan: 4 kishi', max_length=100, null=True)),
                ('architecture', models.TextField(blank=True, default='', help_text="Arxitektura diagrammasi — ASCII/matn ko'rinishida")),
                ('architecture_uz', models.TextField(blank=True, default='', help_text="Arxitektura diagrammasi — ASCII/matn ko'rinishida", null=True)),
                ('architecture_en', models.TextField(blank=True, default='', help_text="Arxitektura diagrammasi — ASCII/matn ko'rinishida", null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Kichik raqam = yuqorida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ish',
                'verbose_name_plural': 'Ishlar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Masalan: 5k+', max_length=50)),
                ('label', models.CharField(help_text='Masalan: Users', max_length=100)),
                ('label_uz', models.CharField(help_text='Masalan: Users', max_length=100, null=True)),
                ('label_en', models.CharField(help_text='Masalan: Users', max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='works.work')),
            ],
            options={
                'verbose_name': 'Raqam',
                'verbose_name_plural': 'Raqamlar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_uz', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('description_uz', models.TextField(blank=True, default='', null=True)),
                ('description_en', models.TextField(blank=True, default='', null=True)),
                ('icon', models.CharField(blank=True, default='', help_text='Ikonka nomi: video, check, book, users, code, star', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='works.work')),
            ],
            options={
                'verbose_name': 'Funksiya',
                'verbose_name_plural': 'Funksiyalar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_title', models.CharField(help_text='Masalan: Video streaming tezligi', max_length=250)),
                ('problem_title_uz', models.CharField(help_text='Masalan: Video streaming tezligi', max_length=250, null=True)),
                ('problem_title_en', models.CharField(help_text='Masalan: Video streaming tezligi', max_length=250, null=True)),
                ('problem_description', models.TextField(blank=True, default='')),
                ('problem_description_uz', models.TextField(blank=True, default='', null=True)),
                ('problem_description_en', models.TextField(blank=True, default='', null=True)),
                ('solution', models.TextField(blank=True, default='')),
                ('solution_uz', models.TextField(blank=True, default='', null=True)),
                ('solution_en', models.TextField(blank=True, default='', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='works.work')),
            ],
            options={
                'verbose_name': 'Muammo va yechim',
                'verbose_name_plural': 'Muammolar va yechimlar',
                'ordering': ['order', 'id'],
            },
        ),
    ]
